backend/django_app/django_app/urls.py
from django.contrib import admin
from django.urls import include, path

handler404 = 'titles.views.page_not_found'
handler500 = 'titles.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('titles.urls')),
]

backend/django_app/titles/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import TitleViewSet, GenreViewSet, TagViewSet, ChapterViewSet
from django.views.generic.base import RedirectView

from titles import views

app_name = 'titles'
handler404 = 'titles.views.page_not_found'

router = DefaultRouter()
router.register(r'titles', TitleViewSet, basename='title')
router.register(r'genres', GenreViewSet)
router.register(r'tags', TagViewSet)
router.register(r'chapters', ChapterViewSet)
urlpatterns = [
    path('', RedirectView.as_view(url='titles/', permanent=False), name='catalog'),
    path('titles/', views.TitleList.as_view(), name='catalog'),
    path('titles/<int:pk>/', views.TitleDetail.as_view(), name='detail'),
    path('api/', include(router.urls)),
]

backend/django_app/titles/models.py
from django.db import models


class NameAbstract(models.Model):
    """
    Модель с полем имени
    """
    name = models.CharField("Название", max_length=255, default="Нет названия")

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Genre(NameAbstract):
    """
    Модель данных для жанров
    """
    class Meta:
        verbose_name = "жанр"
        verbose_name_plural = "Жанры"


class Tag(NameAbstract):
    """
    Модель данных для тегов
    """
    class Meta:
        verbose_name = "тег"
        verbose_name_plural = "Теги"


class Title(NameAbstract):
    """
    Модель данных для тайтла
    """
    description = models.TextField("Описание", default="Нет описания")
    author = models.CharField("Автор", max_length=255, default="Неизвестен")
    year = models.CharField("Год выпуска", max_length=4, default="0000")
    status = models.CharField("Статус выхода", max_length=127, default="Неизвестен")
    type = models.CharField("Тип", max_length=127, default="Неизвестен")
    rating = models.FloatField("Рейтинг", default=0.0)
    mangalib_url = models.CharField("Ссылка на MangaLib", max_length=255)
    remanga_url = models.CharField("Ссылка на ReManga", max_length=255, blank=True)
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    thumbnail = models.URLField("Превью", max_length=200, default="")
    cover = models.URLField("Полная обложка", max_length=200, default="")

    class Meta:
        verbose_name = "тайтл"
        verbose_name_plural = "Тайтлы"


class Chapter(NameAbstract):
    """
    Модель данных для глав тайтлов
    """
    source = models.CharField("Источник", max_length=50, default="Неизвестен")
    release = models.DateField("Дата выпуска")
    translator = models.CharField("Переводчик", max_length=255, default="Неизвестен")
    link = models.URLField("Ссылка", max_length=200)
    manga = models.ForeignKey(Title, on_delete=models.CASCADE, related_name="chapters")

    class Meta:
        verbose_name = "глава"
        verbose_name_plural = "Главы"

backend/django_app/titles/views.py
from django.shortcuts import render
from django.core.serializers import serialize
from django.views import generic
from rest_framework import viewsets, status
from rest_framework.response import Response
from django.db.models import Q
import logging
import json

from .models import Title, Chapter, Genre, Tag, Chapter
from .serializers import TitleSerializer, GenreSerializer, TagSerializer,ChapterSerializer, TitleShortSerializer
from .requests import get_title, get_titles
logger = logging.getLogger(__name__)
parser_url = 'http://192.168.88.201:3000'

class TitleList(generic.ListView):
    """Список тайтлов."""
    model = Title
    template_name = 'titles/index.html'
    paginate_by = 100

    '''def get_queryset(self):
        """
        Выводим только несколько последних новостей.

        Их количество определяется в настройках проекта.
        """
        return self.model.objects.prefetch_related(
            'comment_set'
        )[:settings.NEWS_COUNT_ON_HOME_PAGE]'''

    def get_context_data(self, **kwargs):
        get_titles(parser_url)
        context = super(TitleList, self).get_context_data(**kwargs)
        data = serialize("json", context['title_list'])
        context['json'] = data
        return context


class TitleDetail(generic.DetailView):
    model = Title
    template_name = 'titles/description.html'

    def get_object(self):
        get_title(parser_url, Title.objects.get(pk=self.kwargs['pk']).mangalib_url)
        obj = super().get_object()
        return obj

    def get_context_data(self, **kwargs):
        context = super(TitleDetail, self).get_context_data(**kwargs)
        mangalib_chapters = serialize("json", list(Chapter.objects.all().filter(manga=self.get_object(), source='mangalib')))
        remanga_chapters = serialize("json", list(Chapter.objects.all().filter(manga=self.get_object(), source='remanga')))
        chapters = json.dumps({
            "mangalib": mangalib_chapters,
            "remanga": remanga_chapters
        })
        context['chapters_json'] = chapters
        context['title_json'] = serialize("json", [context['title'], ])
        context['tags_json'] = serialize("json", list(self.object.tags.all()))
        context['genres_json'] = serialize("json", list(self.object.genres.all()))
        return context


class TitleViewSet(viewsets.ModelViewSet):
    queryset = Title.objects.all()
    serializer_class = TitleSerializer

    def get_serializer_class(self):
        if self.action == 'list':
            return TitleShortSerializer
        return TitleSerializer

    def create(self, request, *args, **kwargs):
        # Если пришёл массив объектов
        if isinstance(request.data, list):
            serializer = self.get_serializer(data=request.data, many=True)
            serializer.is_valid(raise_exception=True)
            self.perform_bulk_create(serializer)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        # Обычное поведение для одного объекта
        return super().create(request, *args, **kwargs)

    def perform_bulk_create(self, serializer):
        serializer.save()

    def get_queryset(self):
        queryset = super().get_queryset()
        params = self.request.query_params
        q = Q()

        # Диапазон года
        year_from = params.get('year_from')
        year_to = params.get('year_to')
        if year_from:
            q &= Q(year__gte=year_from)
        if year_to:
            q &= Q(year__lte=year_to)

        # Диапазон рейтинга
        rating_min = params.get('rating_min')
        rating_max = params.get('rating_max')
        if rating_min:
            q &= Q(rating__gte=rating_min)
        if rating_max:
            q &= Q(rating__lte=rating_max)

        # Тип (может быть несколько: ?type=Манга&type=Манхва)
        types = params.getlist('type')
        if types:
            q &= Q(type__in=types)

        # Статус (может быть несколько: ?status=Завершён&status=Онгоинг)
        statuses = params.getlist('status')
        if statuses:
            q &= Q(status__in=statuses)

        # Поиск
        search = params.get('search')
        if search:
            q &= (Q(name__icontains=search) | Q(author__icontains=search))
        queryset = queryset.filter(q).distinct()
        
        # Сортировка
        order_by = params.get('order_by')
        if order_by in ['year', '-year', 'rating', '-rating']:
            queryset = queryset.order_by(order_by)
        return queryset


class GenreViewSet(viewsets.ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer

class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

class ChapterViewSet(viewsets.ModelViewSet):
    queryset = Chapter.objects.all()
    serializer_class = ChapterSerializer

def page_not_found(request, exception):
    return render(request, 'titles/404.html', status=404)


def server_error(request):
    return render(request, 'titles/500.html', status=500)

backend/django_app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block title %}{% endblock %}
	{% block css %}{% endblock %}
</head>
<body>
	{% block body %}{% endblock %}
</body>
</html>

backend/django_app/templates/description.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Описание манги - ALL MANGA</title>
    <link rel="stylesheet" href="styles/style.css">
    <link rel="stylesheet" href="styles/description.css">
</head>
<body>
    <header>
        <img src="images/Logo.svg" alt="Лого сайта" width="140" height="50">
        <nav><a href="index.html">Каталог</a></nav>
    </header>
    <div class="container">
        <aside class="sidebar">
            <img src="#" alt="Обложка манги" width="100%">
        </aside>
        <main class="content">
            <h1>Название</h1>
            <div class="tabs">
                <button class="tab active" data-tab="about">О тайтле</button>
                <button class="tab" data-tab="chapters">Главы</button>
            </div>
            <div id="about" class="tab-content active">
                <div class="description-box">
                    <h3>Описание</h3>
                    <p>Тут будет описание манги...</p>
                </div>
                <div class="tags">
                    <span class="tag">Жанр</span>
                    <span class="tag">Жанр</span>
                    <span class="tag">Жанр</span>
                    <span class="tag">#Тег</span>
                    <span class="tag">#Тег</span>
                    <span class="tag">#Тег</span>
                    <span class="tag">#Тег</span>
                </div>
                <div class="info">
                    <p><strong>Автор:</strong> Фамилия И. О.</p>
                    <p><strong>Год выхода:</strong> 2025</p>
                    <p><strong>Статус:</strong> Онгоинг</p>
                    <p><strong>Рейтинг:</strong> 9.02</p>
                </div>
            </div>
            <div id="chapters" class="tab-content">
                <div class="source-selector">
                    <button id="mangalib" class="source-btn active">MANGALIB</button>
                    <button id="remanga" class="source-btn">Remanga</button>
                </div>
                <h3>Список глав</h3>
                <ul></ul>
            </div>
        </main>
    </div>
    <script src="scripts/script.js"></script>
</body>
</html>

backend/django_app/templates/includes/header.html
{% load static %}
<header>
	<img src="{% static 'img/Logo.svg' %}" alt="Лого сайта" width="140" height="50">
	<nav><a href="{% url 'titles:catalog' %}">Каталог</a></nav>
</header>

backend/django_app/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ALL MANGA</title>
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>
    <header>
        <img src="images/Logo.svg" alt="Лого сайта" width="140" height="50">
        <nav><a href="index.html">Каталог</a></nav>
    </header>
    <div class="container">
        <main class="content">
            <input type="text" id="search" placeholder="Поиск...">
            <div class="catalog" id="catalog"></div>
        </main>
        <aside class="sidebar">
            <h3>Сортировать</h3>
            <label>Год выхода:</label>
            <input type="number" id="yearFrom" placeholder="От" min="1930" max="2026"> 
            <input type="number" id="yearTo" placeholder="До" min="1930" max="2026">
            <label>Рейтинг:</label>
            <input type="number" id="ratingMin" placeholder="Мин" min="0" max="9">
            <input type="number" id="ratingMax" placeholder="Макс" min="1" max="10">
            <br>
            <div class="checkbox-container">
                <label for="popular">Популярность</label>
                <input type="checkbox" id="popular">
            </div>
        
            <h3>Фильтр</h3>
            <label>Жанры</label>
            <select id="genres"><option>Выбрать...</option></select>
            <label>Теги</label>
            <select id="tags"><option>Выбрать...</option></select>
        
            <h3>Возрастной рейтинг</h3>
            <div class="checkbox-group">
                <label><input type="checkbox" name="age" value="none"> Нет</label>
                <label><input type="checkbox" name="age" value="6"> +6</label>
                <label><input type="checkbox" name="age" value="12"> +12</label>
                <label><input type="checkbox" name="age" value="16"> +16</label>
                <label><input type="checkbox" name="age" value="18"> +18</label>
            </div>
        
            <h3>Тип</h3>
            <div class="checkbox-group">
                <label><input type="checkbox" name="type" value="manga"> Манга</label>
                <label><input type="checkbox" name="type" value="manhwa"> Манхва</label>
                <label><input type="checkbox" name="type" value="manhua"> Маньхуа</label>
                <label><input type="checkbox" name="type" value="rumanga"> Руманга</label>
            </div>
        
            <h3>Статус тайтла</h3>
            <div class="checkbox-group">
                <label><input type="checkbox" name="status" value="ongoing"> Онгоинг</label>
                <label><input type="checkbox" name="status" value="announcement"> Анонс</label>
                <label><input type="checkbox" name="status" value="completed"> Завершен</label>
                <label><input type="checkbox" name="status" value="discontinued"> Прекращен</label>
                <label><input type="checkbox" name="status" value="paused"> Приостановлен</label>
            </div>
            <div class="button-container">
                <button id="applyFilters" class="button button-apply">Применить</button>
                <button id="resetFilters" class="button button-reset">Сбросить</button>
            </div>
        </aside>
    </div>
    <script src="scripts/script.js"></script>
</body>
</html>

backend/django_app/templates/titles/description.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Описание манги - ALL MANGA</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/description.css' %}">
{% endblock %}
{% block body %}
{% include "includes/header.html" %}
<div class="container">
    <aside class="sidebar">
        <img src="#" alt="Обложка манги" width="100%">
    </aside>
    <main class="content">
        <h1>Название</h1>
        <div class="tabs">
            <button class="tab active" data-tab="about">О тайтле</button>
            <button class="tab" data-tab="chapters">Главы</button>
        </div>
        <div id="about" class="tab-content active">
            <div class="description-box">
                <h3>Описание</h3>
                <p>Тут будет описание манги...</p>
            </div>
            <div class="tags">
            </div>
            <div class="info">
                <p><strong>Тип:</strong> <span id="manga-type"></span></p> 
                <p><strong>Автор:</strong> <span id="manga-author"></span></p>
                <p><strong>Год:</strong> <span id="manga-year"></span></p>
                <p><strong>Статус:</strong> <span id="manga-status"></span></p>
                <p><strong>Рейтинг:</strong> <span id="manga-rating"></span></p>
            </div>
        </div>
        <div id="chapters" class="tab-content">
            <div class="source-selector">
                <button id="mangalib" class="source-btn active">MANGALIB</button>
                <button id="remanga" class="source-btn">Remanga</button>
            </div>
            <h3>Список глав</h3>
            <ul></ul>
        </div>
    </main>
</div>
{{ title_json|json_script:"title_json" }}
{{ chapters_json|json_script:"chapters_json" }}
{{ tags_json|json_script:"tags_json" }}
{{ genres_json|json_script:"genres_json" }}
<script src="{% static 'js/description.js' %}"></script>
{% endblock %}

backend/django_app/templates/titles/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>ALL MANGA</title>
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %}
{% include "includes/header.html" %}
<div class="container">
    <main class="content">
        <div class="search-content">
            <input type="text" id="search-input" placeholder="Поиск...">
            <button id="search" class="button-search">Поиск</button>
        </div>
        <div class="catalog" id="catalog"></div>
    </main>
    <aside class="sidebar">
        <h3>Сортировать</h3>
            <div class="checkbox-container">
                <label><input type="radio" class="radio" name="browser" id="year" value="year">Год выхода</label>
                <label><input type="radio" class="radio" name="browser" id="rating" value="rating">Рейтинг</label>
            </div>
            
            <div class="checkbox-container">
                <label><input type="radio" class="radio" name="order" id="asc" value="asc">По возрастанию</label>
                <label><input type="radio" class="radio" name="order" id="desc" value="desc">По убыванию</label>
            </div>
    
        <h3>Фильтр</h3>
        {% comment %} <label>Жанры</label>
        <select id="genres"><option>Выбрать...</option></select>
        <label>Теги</label>
        <select id="tags"><option>Выбрать...</option></select> {% endcomment %}
    
        {% comment %} <h3>Возрастной рейтинг</h3>
        <div class="checkbox-group">
            <label><input type="checkbox" name="age" value="none"> Нет</label>
            <label><input type="checkbox" name="age" value="6"> +6</label>
            <label><input type="checkbox" name="age" value="12"> +12</label>
            <label><input type="checkbox" name="age" value="16"> +16</label>
            <label><input type="checkbox" name="age" value="18"> +18</label>
        </div> {% endcomment %}
    
        <h3>Тип</h3>
        <div class="checkbox-group">
            <label><input type="checkbox" name="type" value="Манга"> Манга</label>
            <label><input type="checkbox" name="type" value="Манхва"> Манхва</label>
            <label><input type="checkbox" name="type" value="Маньхуа"> Маньхуа</label>
            <label><input type="checkbox" name="type" value="Руманга"> Руманга</label>
        </div>
    
        <h3>Статус тайтла</h3>
        <div class="checkbox-group">
            <label><input type="checkbox" name="status" value="Онгоинг"> Онгоинг</label>
            <label><input type="checkbox" name="status" value="Анонс"> Анонс</label>
            <label><input type="checkbox" name="status" value="Завершён"> Завершён</label>
            <label><input type="checkbox" name="status" value="Прекращён"> Прекращён</label>
            <label><input type="checkbox" name="status" value="Приостановлен"> Приостановлен</label>
        </div>
        <div class="button-container">
            <button id="applyFilters" class="button button-apply">Применить</button>
            <button id="resetFilters" class="button button-reset">Сбросить</button>
        </div>
    </aside>
</div>
<div id="pagination" class="pagination-container"></div>
{{ json|json_script:"mangaData" }}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}